version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=contas_a_pagar
    volumes:
      - ./postgres_data:/var/lib/postgresql/data